# checkpoint
model_name: "efficient_unet"
checkpoint_path: "../history/efficient_unet.pth"
# dataset
dataset_path: "../nyu_data"
# resolution
resolution: [320, 240]
# transforms
normalize: False
# device
device: "cuda"
# outputs
outputs_dir: "../outputs"
# display
verbose: 500
# other
random_seed: 42
num_workers: 4
pin_memory: True
prefetch_factor: 2
