# dataset
dataset_path: "../nyu_data"
# model
model_name: "dense_unet"
pretrained: True
# resolution
train_resolution: [320, 240]
val_resolution: [320, 240]
# transforms
transforms_level: "light"
# training
num_epochs: 50
batch_size: 8
learning_rate: 0.0001
weight_decay: 0.0001
ema_weight: 0.1
# device
device: "cuda"
# checkpoints
checkpoints_dir: "../checkpoints"
save_checkpoint_per_num_epochs: 5
# display
verbose: 500
# other
random_seed: 42
num_workers: 4
pin_memory: True
prefetch_factor: 2
